2017-07-20 14:05:27,974 [updatedb.py  <module> 33  MainThread ] [INFO ]  Started thread feeders
2017-07-20 14:05:59,945 [common.py  checkstatus 18  MainThread ] [ERROR]  ConnectTimeout(MaxRetryError("HTTPConnectionPool(host='cybercrime-tracker.net', port=80): Max retries exceeded with url: /all.php (Caused by ConnectTimeoutError(<requests.packages.urllib3.connection.HTTPConnection object at 0x110a4b9b0>, 'Connection to cybercrime-tracker.net timed out. (connect timeout=30)'))",),)
2017-07-20 14:06:00,665 [dataplane.py  checkstatus 43  MainThread ] [INFO ]  Source Available-> https://dataplane.org/dnsrd.txt :True
2017-07-20 14:06:01,304 [dataplane.py  checkstatus 43  MainThread ] [INFO ]  Source Available-> https://dataplane.org/dnsrdany.txt :True
2017-07-20 14:06:01,950 [dataplane.py  checkstatus 43  MainThread ] [INFO ]  Source Available-> https://dataplane.org/dnsversion.txt :True
2017-07-20 14:06:02,607 [dataplane.py  checkstatus 43  MainThread ] [INFO ]  Source Available-> https://dataplane.org/sipinvitation.txt :True
2017-07-20 14:06:03,258 [dataplane.py  checkstatus 43  MainThread ] [INFO ]  Source Available-> https://dataplane.org/sipquery.txt :True
2017-07-20 14:06:03,906 [dataplane.py  checkstatus 43  MainThread ] [INFO ]  Source Available-> https://dataplane.org/sipregistration.txt :True
2017-07-20 14:06:05,028 [dataplane.py  checkstatus 43  MainThread ] [INFO ]  Source Available-> https://dataplane.org/sshclient.txt :True
2017-07-20 14:06:05,930 [dataplane.py  checkstatus 43  MainThread ] [INFO ]  Source Available-> https://dataplane.org/sshpwauth.txt :True
2017-07-20 14:06:06,577 [dataplane.py  checkstatus 43  MainThread ] [INFO ]  Source Available-> https://dataplane.org/vncrfb.txt :True
2017-07-20 14:06:38,754 [common.py  checkstatus 18  MainThread ] [ERROR]  ConnectTimeout(MaxRetryError("HTTPConnectionPool(host='cybercrime-tracker.net', port=80): Max retries exceeded with url: /all.php (Caused by ConnectTimeoutError(<requests.packages.urllib3.connection.HTTPConnection object at 0x110ab7978>, 'Connection to cybercrime-tracker.net timed out. (connect timeout=30)'))",),)
2017-07-20 14:06:41,902 [ransomwaretracker.py  getIntelligent 36  MainThread ] [INFO ]  source link is available
2017-07-20 14:06:46,811 [ransomwaretracker.py  parsePage 75  MainThread ] [ERROR]  Eror on gathering intelligent from:/downloads/CW_PS_DOMBL.txt
2017-07-20 14:06:48,660 [ransomwaretracker.py  parsePage 75  MainThread ] [ERROR]  Eror on gathering intelligent from:/downloads/CW_PS_IPBL.txt
2017-07-20 14:06:53,491 [ransomwaretracker.py  parsePage 75  MainThread ] [ERROR]  Eror on gathering intelligent from:/downloads/TC_PS_IPBL.txt
